bonfire_quickstart.md
deploy/clowdapp.yml

This PR modifies `clowdapp.yml` to use a template parameter for the image namespace, defaulting to `cloudservices`. By overriding this value in your Bonfire config, you can use the existing `clowdapp.yml` without needing to make a modified copy for testing local changes.

Allow overriding image namespace

---

pom.xml

This PR addresses https://github.com/RedHatInsights/insights-runtimes-inventory/issues/55, in which it'd be nice to have a code coverage report. I put it behind a maven profile so it can be run when desired.
I took a look through the Quarkus guide for test coverage [[0]](https://quarkus.io/guides/tests-with-coverage), and there's a quarkus-jacoco extension that reports coverage for @QuakusTest classes. The extension can also work with the jacoco-maven-plugin, but this requires a bit of additional config to ignore the @QuarkusTest classes [[1]](https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest). This config will only work if there is at least one @QuarkusTest being run, so at the moment I have it (and the extension) commented out.
Edit: QuarkusTest …

Setup code coverage reporting

---

events/src/main/java/com/redhat/runtimes/inventory/events/EventConsumer.java
rest/pom.xml
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java
rest/src/test/java/com/redhat/runtimes/inventory/web/TestLifecycleManager.java

This PR addresses issue: https://github.com/RedHatInsights/insights-runtimes-inventory/issues/63 (and https://github.com/RedHatInsights/insights-runtimes-inventory/issues/49, kind of)
I added a couple of basic unit tests for the rest component, which checks the response code (and response, if successful) of making a request to the `/instance/` endpoint with both a valid and invalid header. It also makes use of the QuarkusTest annotation, so it runs some test containers. I needed to add the events component as a test dependency so that the database would setup properly, otherwise the test was complaining about not having tables.

Add unit tests for the rest component

---

core/pom.xml
coverage/pom.xml
events/pom.xml
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerTest.java
pom.xml
rest/pom.xml
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java

This PR addresses issue https://github.com/RedHatInsights/insights-runtimes-inventory/issues/65 [0], in which it'd be nice to separate the tests that run testcontainers ("integration tests") from the regular junit tests.
There's a couple issues at the moment with the current test setup. One being that testcontainers could be seen as not a unit test in the traditional sense, as they're more intensive and expensive. Second is that testcontainers doesn't play nicely with all operating systems, so with a team developing on multiple OSs we might want to make these tests opt-in.
The idea with this PR is to tag the test classes that use testcontainers with `integration-test`, and then have extra profiles in the root pom to direct the test flow. The default profile will exclude any test tagged …

Separate unit tests and Quarkus tests into maven profiles

---

core/pom.xml
events/pom.xml
events/src/main/java/com/redhat/runtimes/inventory/events/EventConsumer.java
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerIntegrationTest.java
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerTest.java
events/src/test/java/com/redhat/runtimes/inventory/events/MicrometerAssertionHelper.java
events/src/test/java/com/redhat/runtimes/inventory/events/TestLifecycleManager.java
pom.xml
rest/pom.xml

This PR addresses https://github.com/RedHatInsights/insights-runtimes-inventory/issues/49 [0], in which it'd be nice to have test cases that use TestContainers.
I've enabled the QuarkusTest annotation, and as a base I borrowed some starter code from RedHatInsights/notifications-backend for the TestLifecycleManager [[1]](https://github.com/RedHatInsights/notifications-backend/blob/master/engine/src/test/java/com/redhat/cloud/notifications/TestLifecycleManager.java) and MicrometerAssertionHelper [[2]](https://github.com/RedHatInsights/notifications-backend/blob/master/common/src/test/java/com/redhat/cloud/notifications/MicrometerAssertionHelper.java).
This PR adds three new unit tests.
- `testBasicPostgresTransactions()` uses a JvmInstance from one of the zipped json test files, and …

Add test cases using TestContainers

---

events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerTest.java

I ran into this while testing out retrieval of jar hash information (using the test resource files as input). There are some typos in the attribute names when setting the jar hash information from a jvm instance.
The jar information can look something like:
```
"jars" : [ {
"name" : "",
"version" : "",
"attributes" : {
"sha1Checksum" : "",
"Implementation-Vendor" : "",
"groupId" : "",
"sha256Checksum" : "",
"artifactId" : "",
"sha512Checksum" : "",
"Implementation-Vendor-Id" : "",
"version" : ""
}
} ]
```
And here's an example of what information comes back before & after this commit:
Before:
```
{
id=ba834aa9-8ebb-4a1b-8ea1-520268a060f2,
instance=JvmInstance{[..]},
name='jboss-modules.jar',
groupId='',
vendor='',
version='1.12.0.Final-redhat-00001', 
sha1Checksum='',
sha256Checksum='', …
```

Fix typos when setting the attributes of JarHash

---

events/pom.xml
events/src/main/java/com/redhat/runtimes/inventory/events/EventConsumer.java
events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerIntegrationTest.java
events/src/test/java/com/redhat/runtimes/inventory/events/TestUtils.java
events/src/test/resources/test17.json
rest/pom.xml
rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java

This PR attempts to address part of issue #48 [[0]](https://github.com/RedHatInsights/insights-runtimes-inventory/issues/48), where the rest service should return more data. Specifically, I've added some extra jvm instance related endpoints, and some for jar hashes.
The current implementation of `/instance/` in `DisplayInventory` retrieves the jvm instances that correspond to a specific orgId and hostname, and returns the first index [[1]](https://github.com/RedHatInsights/insights-runtimes-inventory/blob/main/rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java#L78). I've tweaked this so it accepts a jvm instance id and retrieves that singular instance, and added (2) more endpoints:
-  `/instance-ids/` to return all jvm instances matching orgId and hostname
- …

Add jvm instance and jar hash endpoints to the rest service

---

deploy/clowdapp.yml

This will active the profile based on environment name. 
A little caveat is that if I deployed on dev environments, as env name the ephemeral namespace name is passed, where it activates a profile (what does nothing) with the namespace name.

fix: passing environment to quarkus app as profile

---

rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java

This PR addresses issue https://github.com/RedHatInsights/insights-runtimes-inventory/issues/89, in which we don't really need an endpoint for a single jarhash. 
This pr simply removes `/jarhash` (as well as `/jarhash-ids` as it doesn't have a purpose afterwards).

Remove /jarhash and /jarhash-ids endpoints

---

core/src/main/java/com/redhat/runtimes/inventory/models/EapConfiguration.java
core/src/main/java/com/redhat/runtimes/inventory/models/EapInstance.java
core/src/main/java/com/redhat/runtimes/inventory/models/JvmInstance.java

Default hibernate limits for text fields are 255 characters.
Instead set to LOB_DEFAULT (normally 1048576).

Change Text field character limits.

---

core/src/main/java/com/redhat/runtimes/inventory/models/EapConfiguration.java
core/src/main/java/com/redhat/runtimes/inventory/models/EapDeployment.java
core/src/main/java/com/redhat/runtimes/inventory/models/EapInstance.java
events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java
events/src/main/resources/db/migration/V1.0.0__jvm_instance.sql
events/src/test/java/com/redhat/runtimes/inventory/events/TestUtils.java
rest/src/main/java/com/redhat/runtimes/inventory/web/DisplayInventory.java
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java

This PR addresses issue #48 [[0]](https://github.com/RedHatInsights/insights-runtimes-inventory/issues/48), in which it'd be nice to be able to retrieve EapInstance data from the db.
With the recent commits to shuffle around EapInstance and JvmInstance shared fields, the response from a single EapInstance is much smaller. To further shrink this, I've added a query param `includeRaw` that gets cast to a boolean, to control whether or not to return the raw json field.
Example curl commands (tested on localhost):
```
curl -X GET http://127.0.0.1:9087/api/runtimes-inventory-service/v1/eap-instances/\?hostname=freya -H "x-rh-identity:$IDENTITY"
curl -X GET http://127.0.0.1:9087/api/runtimes-inventory-service/v1/eap-instances/\?hostname=freya&includeRaw=false -H "x-rh-identity:$IDENTITY"
``` …

Add endpoints to return EapInstance data

---

deploy/clowdapp.yml
events/src/main/resources/application.properties
pom.xml
rest/src/main/resources/application.properties

This PR adds a `CLOUDWATCH_ENABLED` template parameter which controls whether Cloudwatch is enabled using the quarkus-logging-cloudwatch extension (which I've upgraded). I fixed some properties in application.properties to better show which properties are overridden by Clowder using the clowder-quarkus-config-source extension. I also changed the log stream name so we can distinguish logs between the rest and events pods.

Update Cloudwatch configuration

---

core/pom.xml
core/src/test/java/com/redhat/runtimes/inventory/MockServerConfig.java
core/src/test/resources/rbac-examples/rbac_example_read_access.json
rest/pom.xml
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryTest.java
rest/src/test/java/com/redhat/runtimes/inventory/web/MockServerLifecycleManager.java
rest/src/test/java/com/redhat/runtimes/inventory/web/TestLifecycleManager.java

This PR fixes the integration tests by adding a mock RBAC server derived from https://github.com/RedHatInsights/notifications-backend/commit/7daece1490a0b344ed9bda43047f88e95e65dff5.

Add mock RBAC server for integration tests

---

events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerIT.java
pom.xml
rest/src/test/java/com/redhat/runtimes/inventory/web/ConsoleIdentityProviderIT.java
rest/src/test/java/com/redhat/runtimes/inventory/web/DisplayInventoryIT.java

This PR addresses issue https://github.com/RedHatInsights/insights-runtimes-inventory/issues/123 [[0]](https://github.com/RedHatInsights/insights-runtimes-inventory/issues/123), in which maven-failsafe-plugin should be used for handling the integration tests.
The changes are pretty straightforward, I renamed some of the QuarkusTests to be `*IT.java`, and removed the tag annotations for integration-test now that they aren't needed. The quarkus-jacoco plugin looks to be working even on the unit tests now which is nice, so we can just have the one profile for coverage: `-P coverage`.
How it worked before:
`mvn clean package`
`mvn clean package -P coverage`
`mvn clean package -P integration`
`mvn clean package -P integration-coverage`
How it works now:
`mvn clean package`
`mvn clean package …

Use maven-failsafe-plugin for integration tests

---

deploy/docker/events/Dockerfile

By default Java seems to set `MaxRAMPercentage` to 25%, meaning the events container will run out of memory when it hits 500 MB of the 2 GB given to it.
This change sets it to 80%.

Set JAVA_OPT -XX:MaxRAMPercentage for events container to 80%

---

deploy/clowdapp.yml

In stage and prod environments, we may want to adjust the minimum number of replicas used for our deployments. This PR changes them to a template parameter that can be overridden at runtime.

Add MIN_REPLICAS template parameter

---

deploy/clowdapp.yml
deploy/docker/events/Dockerfile

Increases the events container memory limit to 20GB. With 80% MaxRAMPercentage, this should give us 16GB max for the heap. Print the JVM flags to verify this.
Don't exit on OutOfMemoryError

Increase events memory limit to 20GB

---

deploy/docker/events/Dockerfile
deploy/docker/rest/Dockerfile

This PR converts our container images to use the OpenJDK 17 Runtime UBI base images. This simplifies our Dockerfiles and also allows us to leverage GC tuning configurations designed for containers by Red Hat's JDK team.
Here's the resulting Java command line of the events container (the first `ExitOnOutOfMemoryError` is built-in, we disable it with the `JAVA_OPTS_APPEND` environment variable):
`java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -XX:-ExitOnOutOfMemoryError -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8000 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+PrintFlagsFinal -cp "." -jar /deployments/quarkus-run.jar`
I also corrected the …

Use OpenJDK UBI runtime images

---

events/src/main/resources/db/migration/V1.0.0__jvm_instance.sql

The change, while innocuous, causes flyway to fail checksum comparisons, which causes it to reject the script.

Revert sql comment that breaks previous file checksum.

---

unit_test.sh

The Jenkins pipeline is currently failing due to a java home issue. This will be debugged and tested in: https://github.com/RedHatInsights/insights-runtimes-inventory/pull/138
In the meantime, bring back the old dummy test result from the previous pr_check.sh, which should hopefully get the pr check to pass again.

Fix the pipeline by re-introducing the dummy test result

---

deploy/cryostat.yml

The `IMAGE_TAG` parameter results in Bonfire attempting to use the commit ID for this repo. Rename it to `CRYOSTAT_IMAGE_TAG` to avoid this.

Rename IMAGE_TAG param used for Cryostat

---

deploy/cryostat.yml

Use fixed tags instead of floating tags for Cryostat images to hopefully satisfy app-interface CI. While these are currently all the same for each component, that's not guaranteed.

Use fixed tags for Cryostat images

---

deploy/cryostat.yml

This pull secret allows image pulls from registry.redhat.io. The secret should be present on all environments.

Add rh-registry-pull secret to Cryostat ServiceAccount

---

deploy/cryostat.yml

The `default` namespace here is incorrect. It seems like Kubernetes defaults to the RoleBinding's namespace if none is provided. The API docs don't seem to mention this, but this Kubernetes code seems to indicate it:
https://github.com/kubernetes/kubernetes/blob/246d363ea4bab2ac99a938d0cee73d72fc44de45/pkg/registry/rbac/validation/rule.go#L289-L295
I tested the change in an Ephemeral Environment and it seems to work.

Remove namespace from Cryostat subject

---

bonfire_quickstart.md
deploy/cryostat.yml

Generates a JMX Credentials DB secret used when deploying Cryostat to an Ephemeral Environment. This secret will not be used when deploying to stage or production.
I've also updated the Bonfire instructions to include the new Cryostat component when deploying.

Generate JMX credentials DB secret for EE

---

deploy/cryostat.yml

Use the Kubernetes downward API to inject the Cryostat pod's namespace, which can be used to figure out the hostname of the Cryostat routes. The domain for the routes is still needed and should be passed to the template with the `ROUTE_DOMAIN` parameter, this will be cluster-dependent.
This also fixes the generated JMX credentials password for EE to include alphanumeric characters as well.

Determine Cryostat routes using downward API

---

pom.xml

This PR adds the maven-surefire-junit5-tree-reporter extension, which was formerly tracked by #118.
The plugin adds a nice tree view to the test results for improved readability.
The default setting of `<consoleOutputReporter><disable>true</disable></consoleOutputReporter>` to disables console output, and then is followed up by using settings to show output/stacktraces on test errors and failures.
For the integration tests I opted not to go with the default settings, because of how useful the logs are from hibernate/quarkus/testcontainers in addition to the stacktrace.
Example:
Unit tests:
Integration tests:

Add fabriciorby/maven-surefire-junit5-tree-reporter

---

events/src/main/java/com/redhat/runtimes/inventory/events/ArchiveAnnouncement.java
events/src/test/resources/egg_is_runtimes.json

This changes the ArchiveAnnouncement object to look inside the host property of egg headers for various necessary fields.
I also reverted some changes I had (incorrectly) made to the example egg header file used for tests.
I did add back a url field into it which was missing. This would have to exist to have seen the errors we were seeing in TEST/PROD, so that seems correct.

Fix processing egg headers.

---

deploy/clowdapp.yml
deploy/docker/events/Dockerfile

* Make sure we get >=2 CPUs for the rbi-events pods
* Use the G1 Garbage Collector instead of the Parallel default
* Add explicit resource requests/limits for the rbi-rest pods using existing defaults from prod

Increase CPU resources, use G1 GC

---

deploy/cryostat.yml

Cryostat is currently stuck in stage due to https://github.com/cryostatio/cryostat/issues/1778. This adds a template parameter so we can scale down Cryostat and then scale it back up.

Add parameter to allow scaling down of Cryostat

---

core/src/main/java/com/redhat/runtimes/inventory/models/InsightsMessage.java
core/src/main/java/com/redhat/runtimes/inventory/models/JvmInstance.java
core/src/main/java/com/redhat/runtimes/inventory/models/UpdateInstance.java
core/src/test/java/com/redhat/runtimes/inventory/models/InsightsMessageTest.java
events/pom.xml
events/src/main/java/com/redhat/runtimes/inventory/events/Utils.java
events/src/test/java/com/redhat/runtimes/inventory/events/EventConsumerTest.java

This is based on @aslicerh original PR, but has been refactored to make it slightly more OO.
I've also changed the redacted value to something that doesn't contain * chars that might cause match scripts to choke or require excessive escaping.
Given that this has a homebrew embedded state machine, it needs a proper test suite soon.

Sanitize data before persistence

---

deploy/cryostat.yml

This PR adds basic authentication for Cryostat and Cryostat's Grafana server. It includes some dummy secrets with credentials for Ephemeral Environments:
* Cryostat credentials: `user:pass`
* Grafana credentials: `admin:pass`
In stage/prod environments, these dummy secrets are substituted with real secrets.

Add Basic authentication for Cryostat

---

deploy/cryostat.yml

This PR adds a PVC to be used for Cryostat so that archived recordings can be persisted beyond the lifecycle of the Cryostat pod. This follows the same configuration as the Cryostat Helm Chart when PVC support is enabled. The default is for a 500MiB PVC, but this can be adjusted with the `CRYOSTAT_STORAGE_SIZE` template parameter.

Add Persistent Volume Claim for Cryostat

---

events/src/main/java/com/redhat/runtimes/inventory/events/MetricsConfiguration.java
rest/src/main/java/com/redhat/runtimes/inventory/web/MetricsConfiguration.java

This defines the buckets so we can set rules based on percentiles. (histograms)

feat: add SLO for rest metrics

---

deploy/cryostat.yml

Adds some resource requests and limits for each Cryostat container. The requests match those used by the Cryostat operator. The limits are meant to be sufficiently large, but we may need to increase them depending on the length of the recording we want to do.

Add resource requests/limits for Cryostat

---

deploy/cryostat.yml

I noticed the following error when attempting to scale up a replica set in Ephemeral:
```
Error creating: pods "cryostat-6cbc56f887-bxp72" is forbidden: memory max limit to request ratio per Pod is 2, but provided ratio is 3.031579
```
This PR adjusts all resource requests/limits so the ratio is 2.

Modify Cryostat resource requests/limit ratio

---

deploy/clowdapp.yml
deploy/docker/common/cryostat-run-env.sh

This PR adds password protection for remote JMX connections to the runtimes-inventory pods. The credentials are located in a Kubernetes secret. On ephemeral environments this secret is created with the OpenShift template using a generated password. On stage and prod, these secrets will come from elsewhere.

Require authentication for remote JMX connections

---

deploy/clowdapp.yml
deploy/cryostat.yml
deploy/docker/common/cryostat-run-env.sh

This PR configures the runtimes-inventory pods to use TLS for remote JMX connections. OpenShift's [service serving certificates](https://docs.openshift.com/container-platform/4.14/security/certificates/service-serving-certificate.html) provide the key and certificate.
In order to be usable by Java, the key and certificate need to be added to a keystore. Since Keytool doesn't provide a way to import an existing key into a keystore, I used OpenSSL for this based on this old Red Hat Developer [article](https://developers.redhat.com/blog/2017/11/22/dynamically-creating-java-keystores-openshift#consuming_dynamically_generated_certificates_from_java_applications). This has to be done using an init container that simply runs an OpenSSL command to generate the keystore for use by the main …

Use TLS for remote JMX connections
